#include "aeon_sr/motion/optical_flow_entries.hpp"

#include <Windows.h>
#include <d3dcompiler.h>

#include <cstdio>
#include <cstring>
#include <string>

#include "../../src/motion/optical_flow_shaders.inl"

using namespace aeon_sr;

namespace {

bool compile(const char *entry, const char *quality, ID3DBlob **out)
{
	const D3D_SHADER_MACRO defines[] = { { "AEON_FLOW_QUALITY", quality }, { nullptr, nullptr } };
	ID3DBlob *err = nullptr;
	const HRESULT hr = D3DCompile(kFlowHlsl, std::strlen(kFlowHlsl), "aeon_flow", quality != nullptr ? defines : nullptr,
		nullptr, entry, "cs_5_0", D3DCOMPILE_OPTIMIZATION_LEVEL3, 0, out, &err);
	if (FAILED(hr)) {
		std::fprintf(stderr, "flow_bake: %s (AEON_FLOW_QUALITY %s) failed to compile, hr=0x%08lX\n%s\n", entry,
			quality != nullptr ? quality : "unset", static_cast<unsigned long>(hr),
			err != nullptr ? static_cast<const char *>(err->GetBufferPointer()) : "");
		if (err != nullptr)
			err->Release();
		return false;
	}
	if (err != nullptr)
		err->Release();
	return true;
}

void write_array(std::string &out, const std::string &name, ID3DBlob *blob)
{
	const auto *const p = static_cast<const unsigned char *>(blob->GetBufferPointer());
	const size_t n = blob->GetBufferSize();
	out += "alignas(4) static const unsigned char " + name + "[" + std::to_string(n) + "] = {";
	char hex[8];
	for (size_t i = 0; i < n; ++i) {
		if (i % 24 == 0)
			out += "\n\t";
		std::snprintf(hex, sizeof(hex), "0x%02x,", p[i]);
		out += hex;
	}
	out += "\n};\n";
}

}

int main(int argc, char **argv)
{
	if (argc != 2) {
		std::fprintf(stderr, "usage: aeon_flow_bake <output header>\n");
		return 2;
	}
	std::string out =
		"// Generated by tools/flow_bake from src/motion/optical_flow_shaders.inl when the\n"
		"// add-on is built. Do not edit: change the shader source.\n"
		"#pragma once\n\n#include <cstddef>\n\nnamespace aeon_sr {\nnamespace flow_baked {\n\n"
		"struct Kernel {\n\tconst unsigned char *code;\n\tsize_t size;\n};\n\n";
	std::string matcher = "static const Kernel kMatcher[2][" + std::to_string(flow_entries::kFirstModel) + "] = {\n";
	for (int q = 0; q < 2; ++q) {
		matcher += "\t{";
		for (uint32_t i = 0; i < flow_entries::kFirstModel; ++i) {
			ID3DBlob *blob = nullptr;
			if (!compile(flow_entries::kNames[i], flow_entries::kQualityDefine[q], &blob))
				return 1;
			const std::string name = "k_q" + std::to_string(q) + "_" + flow_entries::kNames[i];
			write_array(out, name, blob);
			blob->Release();
			matcher += " { " + name + ", sizeof(" + name + ") },";
		}
		matcher += " },\n";
	}
	matcher += "};\n\n";
	std::string model = "static const Kernel kModel[" + std::to_string(flow_entries::kCount - flow_entries::kFirstModel) +
		"] = {";
	for (uint32_t i = flow_entries::kFirstModel; i < flow_entries::kCount; ++i) {
		ID3DBlob *blob = nullptr;
		if (!compile(flow_entries::kNames[i], nullptr, &blob))
			return 1;
		const std::string name = std::string("k_model_") + flow_entries::kNames[i];
		write_array(out, name, blob);
		blob->Release();
		model += " { " + name + ", sizeof(" + name + ") },";
	}
	model += " };\n\n";
	out += "\n" + matcher + model + "}\n}\n";

	FILE *f = std::fopen(argv[1], "wb");
	if (f == nullptr) {
		std::fprintf(stderr, "flow_bake: cannot write %s\n", argv[1]);
		return 1;
	}
	const bool ok = std::fwrite(out.data(), 1, out.size(), f) == out.size();
	std::fclose(f);
	return ok ? 0 : 1;
}
